apiVersion: v2
name: event-bus
description: A Helm chart for rabbit mq event bus.
type: application
version: 0.1.0
appVersion: 0.0.1
dependencies:
  - name: rabbitmq
    version: 16.0.13
    repository: "@bitnami"