kube-prometheus-stack:
  nodeExporter:
    enabled: false

  grafana:
    service:
      type: LoadBalancer
      port: 80
    adminUser: admin
    adminPassword: prom-operator

    additionalDataSources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-query-frontend.monitoring.svc.cluster.local:3200

  prometheus:
    service:
      type: LoadBalancer
      port: 9090

  alertmanager:
    service:
      type: LoadBalancer
      port: 9093

tempo-distributed:
  enabled: true
  fullnameOverride: tempo

  traces:
    otlp:
      http:
        enabled: true
      grpc:
        enabled: true

  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://grafana-prometheus-kube-pr-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
    storagePath: /var/tempo/generator
    resources: {}
    persistence:
      enabled: false

