apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apis.fullname" . }}
  labels:
    {{- include "apis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "apis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apis.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command: [ "sh", "-c" ]
          args:
            - |
              echo "⏳ Waiting for RabbitMQ port 5672..."
              until nc -z dev-rbt-mq-rabbitmq.event-bus.svc.cluster.local 5672; do
                echo "RabbitMQ not ready yet, retrying..."
                sleep 5
              done
              echo "✅ RabbitMQ port is open!"
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          